module.exports = {
    getNickname: function(){
        let size = '';
        let sizeClass = Math.floor(Math.random() * 3);
        if(sizeClass === 0){
            size = sizesSmall[Math.floor(Math.random() * sizesSmall.length)] + ' ';
        } else if (size === 1){
            size = sizesBig[Math.floor(Math.random() * sizesBig.length)] + ' ';
        }
    
        let color = colors[Math.floor(Math.random() * colors.length)] + ' ';
        let animal = animals[Math.floor(Math.random() * colors.length)];
    
        return size + color + animal;
    }
}

var sizesSmall = [
    'Microscopic',
    'Tiny',
    'Miniscule',
    'Mini',
    'Petite',
    'Little',
    'Small'
];

var sizesBig = [
    'Big',
    'Large',
    'Huge',
    'Giant',
    'Gigantic',
    'Enormous',
    'Colossal'
];

var colors = [  
    'Black',
    'Grey',
    'White',
    'Red',
    'Orange',
    'Yellow',
    'Green',
    'Blue',
    'Indigo',
    'Violet',
    'Purple',
    'Pink',
    'Cyan',
    'Magenta',
];

var animals = [
    'Aardvark',
    'Albatross',
    'Alligator',
    'Ant',
    'Antelope',
    'Armadillo',
    'Ape',
    'Baboon',
    'Badger',
    'Barracuda',
    'Bat',
    'Bear',
    'Beaver',
    'Beetle',
    'Bird',
    'Bison',
    'Boar',
    'Buffalo',
    'Bee',
    'Butterfly',
    'Camel',
    'Cat',
    'Caterpillar',
    'Centipede',
    'Chameleon',
    'Cheetah',
    'Chicken',
    'Cimpanzee',
    'Chipmunk',
    'Cougar',
    'Cow',
    'Coyote',
    'Crab',
    'Crocodile',
    'Deer',
    'Dingo',
    'Dodo',
    'Dog',
    'Dolphin',
    'Donkey',
    'Dragonfly',
    'Duck',
    'Eagle',
    'Elephant',
    'Eel',
    'Falcon',
    'Ferret',
    'Fish',
    'Flamingo',
    'Fly',
    'Fox',
    'Frog',
    'Gecko',
    'Gerbil',
    'Giraffe',
    'Goat',
    'Goose',
    'Gorilla',
    'Grasshopper',
    'Hamster',
    'Hare',
    'Hedgehog',
    'Hippopotamus',
    'Horse',
    'Hummingbird',
    'Hyena',
    'Iguana',
    'Jackal',
    'Jaguar',
    'Jellyfish',
    'Kangaroo',
    'Koala',
    'Ladybug',
    'Lemur',
    'Leopard',
    'Lion',
    'Lizard',
    'Llama',
    'Lobster',
    'Lynx',
    'Millipede',
    'Mole',
    'Monkey',
    'Moose',
    'Moth',
    'Mouse',
    'Octopus',
    'Ostrich',
    'Otter',
    'Panther',
    'Parrot',
    'Peacock',
    'Pelican',
    'Penguin',
    'Pig',
    'Piranha',
    'Platypus',
    'Porcupine',
    'Puma',
    'Python',
    'Rabbit',
    'Racoon',
    'Rattlesnake',
    'Reindeer',
    'Rhinoceros',
    'Salamander',
    'Scorpion',
    'Seahorse',
    'Seal',
    'Sheep',
    'Shark',
    'Sloth',
    'Snail',
    'Snake',
    'Squid',
    'Squirrel',
    'Starfish',
    'Stingray',
    'Swan',
    'Termite',
    'Tiger',
    'Tortoise',
    'Toucan',
    'Toad',
    'Turkey',
    'Vulture',
    'Walrus',
    'Whale',
    'Wasp',
    'Weasel',
    'Wolf',
    'Wombat',
    'Woodpecker',
    'Yak',
    'Zebra'
];